<?php
$tab_lang = array("French" => array("menu" => array("Index" => "Index",
													"Profil" => "Profil",
													"Upload" => "Uploader un Torrent",
													"Torrent" => "Parcourir les Torrent",
													"MP" => "Messagerie Interne",
													"Logout" => "Déconnection"
													),
									"site" => array("Activ_acc" => "Votre compte a bien été activé.",
													"Err_Activ_acc" => "La clé de validation est invalide, ou a déjà ete utilisée",
													"MP_liste" => "Liste de vos messages privés :",
													"MP_nonew" => "Pas de nouveau message = pas d'ami.<br />Désolé, revenez plus tard ;)<br /><br />",
													"list_msg_1t" => "Lu",
													"list_msg_2t" => "De :",
													"list_msg_3t" => "Titre :",
													"list_msg_4t" => "Date :",
													"My_mess" => "Mes messages",
													"New_mess" => "Composer un message",
													"Order_mess" => "Ordonner les messages par :",
                                                    "recherche_rapide" => "Recherche rapide",
                                                    "msg_preview" => "Appercu du message",
                                                    "msg_fdest" => "Trouver un destinataire...",
                                                    "pro_log" => "Nom d'utilisateur :",
                                                    "pro_pass" => "Mot de passe",
                                                    "pro_pass2" => "Confirmer mot de passe",
                                                    "pro_client" => "Client",
                                                    "pro_mail" => "E-Mail",
                                                    "pro_location" => "Localisation",
                                                    "pro_style" => "Style",
                                                    "pro_lang" => "Langue",
                                                    "rechercher" => "Rechercher"
													),
									"categories" => array("Categorie-1" => "Tous",
													"Categorie0" => "Autres",
													"Categorie1" => "Animes",
													"Categorie2" => "Livres",
													"Categorie3" => "Jeux",
													"Categorie4" => "Films",
													"Categorie5" => "Musiques",
													"Categorie6" => "Images",
													"Categorie7" => "Logiciels",
													"Categorie8" => "TV",
													"Ncat1" => "Nom",
													"Ncat2" => "Categorie",
													"Ncat3" => "Posteur",
													"Ncat4" => "Taille",
													"Ncat5" => "Date"
													),	
									),
				  "English" => array("menu" => array("Index" => "Index",
				   									 "Profil" => "Profil",
				 									 "Upload" => "Upload",
													 "Torrent" => "Torrent",
													 "MP" => "Private Message",
													 "Logout" => "Logout"
													 ),
									"site" => array("Activ_acc" => "Account actived.",
													"Err_Activ_acc" => "Invalid key or already in use.",
													"MP_liste" => "List of your PM :",
													"MP_nonew" => "No new message<br /><br />",
													"list_msg_1t" => "Read",
													"list_msg_2t" => "From:",
													"list_msg_3t" => "Title :",
													"list_msg_4t" => "Date :",
													"My_mess" => "My messages",
													"New_mess" => "New message",
													"msg_send" => "Send by",
													"msg_corec_sup" => "Message correctly deleted",
													"msg_no_sup" => "Error : can't delete",
													"msg_enterit" => "Enter your message :",
													"msg_dest" => "To :",
													"msg_from" => "From :",
													"msg_titre" => "Title :",
													"msg_contenu" => "Body :",
													"msg_preview" => "Previous message",
													"Order_mess" => "Order Message by :",
                                                    "recherche_rapide" => "Fast search",
                                                    "msg_fdest" => "Send to...",
                                                    "msg_preview" => "Preview of the message",
                                                    "pro_log" => "Username :",
                                                    "pro_pass" => "Password :",
                                                    "pro_pass2" => "Confirm Password",
                                                    "pro_client" => "Client",
                                                    "pro_mail" => "E-Mail",
                                                    "pro_location" => "Location",
                                                    "pro_style" => "Style",
                                                    "pro_lang" => "Langage",
                                                    "rechercher" => "Search"
													),
									"categories" => array("Categorie-1" => "All",
													"Categorie0" => "Others",
													"Categorie1" => "Animes",
													"Categorie2" => "Books",
													"Categorie3" => "Games",
													"Categorie4" => "Movies",
													"Categorie5" => "Musics",
													"Categorie6" => "Pictures",
													"Categorie7" => "Software",
													"Categorie8" => "TV",
													"Ncat1" => "Name",
													"Ncat2" => "Category",
													"Ncat3" => "Poster",
													"Ncat4" => "Size",
													"Ncat5" => "Date"
													),	
									),
					);
?>